// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybegrvsvhfdlqsxqzbji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZWdydnN2aGZkbHFzeHF6YmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNjU1MzksImV4cCI6MjA4Mzc0MTUzOX0.fp-nqKF1oxuqC-thBzzl_n3d5nJepwUc6lK4Bhns80U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use PKCE so OAuth callbacks return ?code=... (not #access_token=...)
    flowType: 'pkce',
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});